### ISSUE TITLE
Pricing on tiers.MD unclear

### ISSUE THREAD

**Issue by cloudonix-eric** [alongalky/eureka-cli-node#33]
Although the comment add $ to pricing was fulfilled, it does make it more confusing.

The company site says " $0.054 per core / hour" so I presume that when the price column says 5.4 it means US Cents, not $ cents ($5.4 vs $0.054).
Suggestion is to stick with the format on the website and remove the word cents completely thus it would be:   $0.054  through $3.469 (and not ~3 hundred and forty seven dollars)

**Comment by alongalky** [comment]
Agreed, see PR #34
